### ISSUE TITLE
Write Remote command Runner.

### ISSUE THREAD

**Issue by pahaz** [pyinvoke/invoke#218]

**Comment by sophacles** [comment]
@pahaz - invoke is intended to be the base of the next generation fabric ( http://www.fabfile.org/ ), so that's definitely in the works, albeit invoke may not have the remote command running built-in, but rather fabric will use invoke in the context of remote command running.

@bitprophet will have to chime in on exact plan details.

**Comment by bitprophet** [comment]
Correct, Fabric v2 will include Runner subclasses that use Paramiko to run commands remotely. I plan to hack on that this month in prep for PyCon, stay tuned!

**Comment by balavec** [comment]
+1
