### ISSUE TITLE
pip dev installation doesn't work

### ISSUE THREAD

**Issue by nchammas** [pyinvoke/invoke#220]
Just tried the [installation instructions here](http://www.pyinvoke.org/installing.html#getting-the-development-version-without-source-control):

```
$ pip install invoke==dev
Downloading/unpacking invoke==dev
  Could not find a version that satisfies the requirement invoke==dev (from versions: 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.9.0)
Cleaning up...
No distributions matching the version for invoke==dev
Storing debug log for failure in /path/.pip/pip.log
```

Are the docs incorrect, or is something wrong with the PyPI setup?

**Comment by bitprophet** [comment]
I feel like something PyPI did broke this in the past, perhaps it has happened again, I'll check. Thanks for the tip-off!

**Comment by bitprophet** [comment]
Yes, it was something PyPI changed on their end, I was remembering how this broke for the Fabric package back in January. Same deal here. Just updated the setting for Invoke's entry (plus all my other projects, heh).

The next time I upload a release it should reset the internal values used for `==dev` and it should start working again. I'm going to be uploading a release in the next few days hopefully, so that'll be then. Thanks for your patience (and again, for the report)!

**Comment by nchammas** [comment]
Sounds good. Thank you for the prompt response!

**Comment by bitprophet** [comment]
Bugger, I just uploaded 0.10 but the `urls` section on PyPI still looks blank and `pip install invoke==dev` still doesn't work. Will have to go doublecheck with my PyPI buddies (being connected is pretty useful sometimes...).

**Comment by bitprophet** [comment]
OK, there was another bug on their end which they've just fixed, so e.g. `pip install invoke==dev --allow-unverified invoke` works for me now. (Depending on pip version you may need `--allow-unverified invoke` for it to work, I've updated the install snippet in README to make this clear.)
