### ISSUE TITLE
Access task parameter from pre-tasks

### ISSUE THREAD

**Issue by tschijnmo** [pyinvoke/invoke#229]
This issue is in part linked to issue #228. Currently in the documentation, the way to add pre-tasks to a task is via the decorator

    @task(pre=[call(the_pre_task, param=the_param_value)])
    def another_task(param2):

In cases where `the_param_value` should have some dependency upon `param2`, for instance if we put `param2 + '.txt'` into the place of `the_param_value`, that would be illegal Python due to the scoping rules. So could you please help me if there is some way to make the pre-tasks able to read the parameters given to the main task? This would be very helpful to the possible scenarios in issue #228 I guess. Thank you so much for your help!

Regards,

Tschijnmo

**Comment by bitprophet** [comment]
Yea, this is tough, isn't it. As-is, the pre/post task stuff is pretty basic, and is "compile time" based, as you saw, so "run time" data like main-task params isn't and really *can't* be available.

If we step back and look at what's really going on, it's not "what was `param2` when `another_task` was called", but it's "what is *going to go into* `param2` *when* `another_task` gets called".

Which is thus the parser context (when one is calling the task from the CLI). So it  comes down to "how much of the greater context do we hand to pre/post tasks".

Using [contextualized tasks](http://docs.pyinvoke.org/en/0.10.1/concepts/context.html) probably helps solve this, presuming we add the parser data to the context (I don't think we do this yet but it makes sense to, possibly in a cleaned-up fashion). I.e. it allows pre/post tasks to have a view into the parser results for their main task.

However for maximum flexibility we'd probably still need some language in `call()` acting as shorthand for "whatever the value is for the main task's `blah` parameter". Not sure what that would look like yet.

**Comment by tschijnmo** [comment]
I guess adding some language to `call()` so that we can declare something for the value of the main tasks parameters would be both very nice and very flexible. But maybe it has a problem of being a little bit hard to implement. For instance, if the value of the `blah` parameter of the main task is implemented as something like `call(the_pre_task, param=main_task_param('blah')`, and what we actually need is the value of `blah + '.txt'`. Then the addition operator has to be implemented for the proxy object returned by `main_task_param` as well to delegate to the actual evaluation, which is hard and not really elegant. Or maybe the function could be implemented to be able to accept a function as another argument for the action of the decoration, then it could be something like `main_task_param('blah', lambda x: x + '.txt')`. Any ideas?

Maybe there might be a temporary alternative that might be a lot easier to implement, adding a function to call another task within a task. In this way, if `another_task` needs to call the pretask with parameter `param2 + '.txt', in its body, we can add a statement like

```
ctx.run_task(the_pre_task, param=param2 + '.txt')
```

In this way, rather than declarative specification of pretasks in the decorator, we have an imperative way of invoking other tasks in another task. This might also be helpful for looping the same task over a range of parameters. We could have something like

```
for i in values:
    ctx.run_task(the_pre_task, param=i)
    continue
```

In this vein, maybe the parallel execution can at least be syntactically possible, with something like,

```
ctx.run_tasks_in_parallel(call(the_pre_task, param=i) for i in values)
```

Since I am very new to invoke, I am not quite sure if these slightly imperative way to pre-tasks is in harmony with the rest of invoke, although it does seem a lot simpler to implement than the adding things to the decorator. Any ideas? Thank you!

**Comment by bitprophet** [comment]
Yes, having tasks called by other tasks directly instead of implicitly via pre/post hooks, is absolutely a thing that is planned (see #170, which I think I also linked in your other ticket) because pre/post are only useful in some contexts (they're effectively syntactic sugar / shorthand, in line with true Makefiles and the like. Direct invocation of other tasks is always necessary.

And to be honest, it strikes me as the "right answer" for this particular corner case - "hey, I need <complex thing involving pre/post>" -> "just call them directly".

Only counterargument is the potential deduping around pre/post tasks (i.e. say you want a cleanup task, then a "main work" task running N>1 times across some parameterization, and the cleanup task only wants to run once ever) but that can also be handled, somehow, in the "inner call" most likely (such as adding tracking to the call mechanism so you can indicate things like "only run once per session" - a feature Fabric 1 has had forever, albeit implemented kinda grossly.)

Given all that I think yea, let's close this and just focus the energy on #170 :)
