### ISSUE TITLE
There should be a way to exit from a task with an error message without a traceback

### ISSUE THREAD

**Issue by frol** [pyinvoke/invoke#269]
I am validating some arguments inside of a task and I want to exit gracefully with an error message.

Digging into the code showed that it only handles `invoke.exceptions.Failure` in https://github.com/pyinvoke/invoke/blob/master/invoke/cli.py#L432

At this point, I worked around this with the following hack:

``` python
import logging

from invoke.exceptions import Failure
from invoke.runner import Result

class ConfigError(Failure):

    def __init__(self, msg):
        logging.error(msg)
        super(ConfigError, self).__init__(
            Result(stdout='', stderr='', exited=1, pty=None)
        )
```

and then I can

``` python
raise ConfigError("my error message")
```

But I would rather prefer to have a built-in Invoke exception that will just exit with an error and exit code.

**Comment by frol** [comment]
Today, I have noticed that the master branch has quite a few fixes, but also it has some internal changes, so my workaround will be the following:

```python
import logging

from invoke.exceptions import Failure
from invoke.runners import Result

class ConfigError(Failure):

    def __init__(self, msg):
        logging.error(msg)
        super(ConfigError, self).__init__(
            Result(commands='', stdout='', stderr='', exited=1, pty=None)
        )
```

**Comment by bitprophet** [comment]
History: Invoke's predecessor used an `abort` function which did this; we moved away from that here because encouraging (and using internally) what amounted to `sys.exit(message)`, made it harder to catch non-critical failures when running tasks as library code - everything turned into `SystemExit`.

So, that's why we started with just `raise Failure` and such - easier to start with per-failure-case exceptions and then layer catching/logging on top as needed.

That said,

* Having real logging integration is planned for pre-1.0 (see https://github.com/fabric/fabric/issues/57 which will be made into an Invoke-specific ticket soon most likely)
* Yes, having a useful "just log an error and exit" method is probably still useful - but I wonder what % of the use case is served by literal use of `sys.exit`? (Disregarding that `logging.error(x)` isn't always exactly the same as `print >>sys.stderr, x`, of course)
* Your workaround seems like it'd still end in a traceback, you're just adding the log emit to it - correct? The historical use case is the one where you want *just* an error message and *no* traceback - which might be distinct from your use case?

**Comment by frol** [comment]
I agree that both `abort` and `sys.exit` are evil, which is why I use an exception in my workaround. My workaround is ugly, but it works for me. It exploits the internals of Invoke which catch `Failure` exception and does `sys.exit()`. I could have made a function with logging and `sys.exit()` instead, but as I have mentioned in the beginning, I think that there should be only one `sys.exit()` in the program and it is in Invoke cli entry point.

**Comment by indera** [comment]
abort() also had nice color support https://github.com/fabric/fabric/blob/fa15c4dc5524e24a7016a4f33e1a3bae7f72455d/fabric/utils.py#L29

**Comment by bitprophet** [comment]
This got obviated by #476 and #481
