### ISSUE TITLE
Is PyInvoke supported on Windows?

### ISSUE THREAD

**Issue by eliasdorneles** [pyinvoke/invoke#360]
Hey folks, sorry if this is the wrong place to ask but I couldn't find another channel.

I've noticed there is an `appveyor.yml` with a Windows continuous integration build configured, so I assume there is some support on Windows.
In case it's supported on Windows, perhaps it should be listed on [`setup.py` trove classifiers](https://github.com/pyinvoke/invoke/blob/master/setup.py#L52)?

Thank you!

**Comment by bitprophet** [comment]
Good catch, I guess because we started life without Windows support, it never made it in the classifiers. Thanks!

We definitely do support it; it's a 2nd-class citizen sometimes (insofar as I personally don't check appveyor often & am unable to do Windows debugging locally) but I will always merge fixes that folks (especially one of my more active contributors, who is a Windows-only user) say works for them, as long as I can prove it's not harming the POSIX side of things.
