### ISSUE TITLE
Support for IPython5

### ISSUE THREAD

**Issue by jarekwg** [pyinvoke/invoke#374]
Invoke has become unusable for firing up an IPython shell with the release of IPython5.

The support was already shonky in the past - `ctrl+c` was exiting the interpreter when it shouldn't've been.

But now it completely freaks on any hotkey/navigtationkey input. eg. arrow keys, copypasting, enter, etc.

Hope this can be fixed! :)

**Comment by bitprophet** [comment]
Guessing a variant on the existing issues from #289: tl;dr we shook up how I/O is processed to enable some power features, but some edge cases break because of it. Going to close this and drop a note there adding IPython5 to the list of "stuff that should work before we consider the issue fixed". thanks for the report!
