### ISSUE TITLE
Error on passing task to other task

### ISSUE THREAD

**Issue by Lense** [pyinvoke/invoke#376]
``` python
from invoke import task

@task
def preTask(ctx):
    print("preTask")

@task
def testTask(ctx, otherTask=preTask):
    print("otherTask @ ", otherTask)
```

spits out

```
Traceback (most recent call last):
  File "/usr/bin/inv", line 11, in <module>
    sys.exit(program.run())
  File "/usr/lib/python2.7/site-packages/invoke/program.py", line 269, in run
    self._parse(argv)
  File "/usr/lib/python2.7/site-packages/invoke/program.py", line 329, in _parse
    self.parse_tasks()
  File "/usr/lib/python2.7/site-packages/invoke/program.py", line 490, in parse_tasks
    self.parser = Parser(contexts=self.collection.to_contexts())
  File "/usr/lib/python2.7/site-packages/invoke/collection.py", line 325, in to_contexts
    name=primary, aliases=aliases, args=task.get_arguments()
  File "/usr/lib/python2.7/site-packages/invoke/tasks.py", line 205, in get_arguments
    new_arg = Argument(**self.arg_opts(name, default, taken_names))
  File "/usr/lib/python2.7/site-packages/invoke/tasks.py", line 180, in arg_opts
    if default not in (None, NO_DEFAULT):
  File "/usr/lib/python2.7/site-packages/invoke/tasks.py", line 83, in __eq__
    if self.name != other.name:
AttributeError: 'NoneType' object has no attribute 'name'
```

I was originally doing something really dumb because I didn't understand how invoke worked, but I came across this weird case. Feel free to close this.

**Comment by bitprophet** [comment]
Huh, interesting, I think this is because the value you're passing in the signature of `testTask` is another Task object, and the argument examination stuff obviously didn't anticipate that. Thanks for the report!

Perhaps more deeply, `__eq__` may not be well implemented for Task objects - it should say "nope, not equal" if the other object is `None`. 🤔

**Comment by jr-minnaar** [comment]
Hi, while testing/researching inspect.Signature for #357, I also came across this issue.

I'm still making my way through the codebase and don't yet fully understand why the \__eq\__ method fails when a task is passed as an argument, but I've found two solutions that stops it from failing:

1. Add type checking to \__eq\__
    ```
    if not isinstance(other, (Task, Call)):
        return False
    ```

2.  Return False on None and when 'name' attribute does not exist
    ```
    if other is None:
        return False

    if not getattr(other, 'name', None):
        return False
    ```

I suspect 1 is the better solution, but I don't know Invoke well enough to be sure. Either way, this is indeed "Low-hanging Fruit", and I've got a branch (with updated tests) for both approaches.

However, I've got a suspicion that this only treats the symptom, and that the real cause is somehow related to the argspec/arg_opts logic.

**Comment by jr-minnaar** [comment]
I've figured out how to properly debug Invoke tasks and located the root cause. Turns out there is nothing complicated about this issue :-)

Task.arg_opts simply tries to infer the type of the default value, but first it checks to make sure that the default is not None. If the default happens to be a Task instance, this check calls it's __eq__ function which breaks because it can't deal with anything else besides a Task instance (or more precisely, an object with a 'name' and a 'body' attribute).

I've opened a pull request that fixes this issue for your review.

**Comment by bitprophet** [comment]
Thanks @jr-minnaar - will look that over when I get to wrapping up 0.12.3.

**Comment by kuwv** [comment]
#906

**Comment by bitprophet** [comment]
Rolling into #906 which includes the fix and a changelog entry for this issue.
