### ISSUE TITLE
REQUEST: Implement --list-namespaces

### ISSUE THREAD

**Issue by Zeioth** [pyinvoke/invoke#379]
Right now the only way to filter namespaces is something like:

    invoke --list | grep myNamespace

This is ok when you have 5 or 10 taks but with 100+ could be a problem. Something like:

    invoke --list-namespaces

Might be an elegant solution. What do you think? Also it would be cool to be able to document a namespace, the same way than tasks and parameters.

**Comment by bitprophet** [comment]
Any particular reason this got closed? I actually agree with the premise & can't find other open tickets specifically about this. Useful namespace/subcollection functionality like this is definitely something we want eventually (organizing nontrivial task trees is a core feature), and shouldn't be very hard to implement due to how Collection and friends are designed.

**Comment by bitprophet** [comment]
Not sure why I didn't find it earlier, but #33 is probably the right 'master ticket' for this. Rolling into that one!
