### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by kespindler** [pyinvoke/invoke#381]
Is anyone aware of a web interface for invoke? Looking around on google finds no hits.

**Comment by bitprophet** [comment]
@kespindler Usually a Web interface for "execute arbitrary command-line or scripting language scripts" is just "whichever continuous integration tool you like best" :) E.g. Jenkins, Buildbot, Rundeck, etc.

I don't know of any Invoke-specific tools, regardless, but I'd bet it's due to the above property :)

Closing this as "not actionable" but not locking discussion or anything.
