### ISSUE TITLE
using py.test to test a program that calls an invoke task throws an error

### ISSUE THREAD

**Issue by cheungnj** [pyinvoke/invoke#415]
I'm using [cookiecutter](https://github.com/audreyr/cookiecutter) which is a command line project generation utility. Cookiecutter has `post-hooks` which are scripts / python modules that can run after your project has been generated to do additional project configuration such as installing python package requirements. For my specific post-hook, I use invoke to install python package requirements.

When I generate the project from my terminal, invoke installs the packages easily. However, when I use py.test to run cookiecutter followed by the invoke post-hook, I get this stack trace:
```
-   File "/tmp/test/test_project/env/lib/python2.7/site-packages/invoke/context.py", line 60, in run
-     return runner_class(context=self).run(command, **kwargs)
-   File "/tmp/test/test_project/env/lib/python2.7/site-packages/invoke/runners.py", line 256, in run
-     return self._run_body(command, **kwargs)
-   File "/tmp/test/test_project/env/lib/python2.7/site-packages/invoke/runners.py", line 358, in _run_body
-     raise ThreadException(thread_exceptions)
- invoke.exceptions.ThreadException:
- Saw 1 exceptions within threads (IOError):
-
-
- Thread args: {'kwargs': {'echo': None,
-             'input_': <open file '<stdin>', mode 'r' at 0x7f92f51270c0>,
-             'output': <open file '<stdout>', mode 'w' at 0x7f92f5127150>},
-  'target': <bound method Local.handle_stdin of <invoke.runners.Local object at 0x16e53d0>>}
-
- Traceback (most recent call last):
-
-   File "/tmp/test/test_project/env/lib/python2.7/site-packages/invoke/util.py", line 125, in run
-     super(ExceptionHandlingThread, self).run()
-
-   File "/usr/lib64/python2.7/threading.py", line 764, in run
-     self.__target(*self.__args, **self.__kwargs)
-
-   File "/tmp/test/test_project/env/lib/python2.7/site-packages/invoke/runners.py", line 621, in handle_stdin
-     data = self.read_our_stdin(input_)
-
-   File "/tmp/test/test_project/env/lib/python2.7/site-packages/invoke/runners.py", line 583, in read_our_stdin
-     bytes_ = input_.read(bytes_to_read(input_))
-
-   File "/tmp/test/test_project/env/lib/python2.7/site-packages/invoke/platform.py", line 162, in bytes_to_read
-     return struct.unpack('h', fcntl.ioctl(input_, termios.FIONREAD, "  "))[0]
-
- IOError: [Errno 25] Inappropriate ioctl for device
```

Is the IOError expected behavior because I'm calling `invoke` from another library (`cookiecutter`) which is being called from yet another library (`py.test`)?

**Comment by bitprophet** [comment]
It shouldn't be that there's multiple libraries involved, specifically, and more that `py.test` is probably doing "things" to `sys.stdin`. (Note the middle of the trace is the method `read_our_stdin` - that's Invoke trying to mirror your terminal's stdin to the subprocess'.)

Test harnesses like py.test often replace `sys.stdin/out/err` with their own objects for the purposes of capturing and/or injecting data. IIRC we attempt to perform tests on the streams to see if they look like a "real" terminal, which may not be catching whatever `py.test` is doing here.

I looked and yea, we currently run a function called `has_fileno`, since typically only real streams have a `fileno()` method/attribute. If I were you I'd poke briefly at the value and type of `sys.stdin` as the code enters `invoke.runners.Runner.read_our_stdin` and that might yield a clue and/or suggest additional tests we can run to avoid this.

E.g. they may be exposing a `fileno` even though they probably can't yield a real file descriptor from it.

----

I also need to add an FAQ about this since it comes up occasionally. Thanks for the report!

**Comment by cheungnj** [comment]
This was very informative and thank you for the quick response! I guess I'll start my debugging with `invoke.runners.Runner.read_our_stdin`

**Comment by bitprophet** [comment]
Minor correction, check the value of `_input` (an arg passed to that method), though I assume you'd know if you were manually reassigning the value (it's the argument `in_stream` to `run()`, iirc. `sys.stdin` is simply the default value.)

**Comment by cheungnj** [comment]
I resolved the issue by using py.io directly instead of using the `capfd` py.test fixture. `capfd` uses py.io.StdCaptureFD under the hood so I use that directly and tell it not to modify stdin.
