### ISSUE TITLE
Optional flag values don't work as documented

### ISSUE THREAD

**Issue by ouroboroscoding** [pyinvoke/invoke#416]
Given this documentation (http://docs.pyinvoke.org/en/latest/concepts/cli/intro.html#optional-flag-values) and the following program

`@task`
`def import_auth(ctx, new=False):`

I would expect all these calls to work

`invoke import_auth`
`invoke import_auth --new`
`invoke import_auth --new=test`

But unfortunately only the first two work, the last results in

`No idea what 'test' is!`

Even calling the following results in the same error

`invoke import_auth "--new=test"`

Invoke simply refuses to associate the text "test" with the argument "new".

I can change the code to the following

`@task`
`def import_auth(ctx, new)`

But now I am stuck explicitly setting new as --new=true or --new=false and having to parse this input myself.

Please advise, why does this not work as documented? And what does the reference to "kind" mean in the sentence:

"If it is given with a value (invoke compile --log=foo.log) then the value is stored normally (including honoring **kind** if it was specified)."

I have been unable to find any other reference to this or how to make it work.

**Comment by bitprophet** [comment]
Thanks for the report!

I can confirm this locally. Not sure exactly what's going on; offhand I wondered if the issue was supplying a boolean default value instead of a string one, but no, setting it to a string is equally broken in a different way.

The odd thing is that this clearly works at some level as we use it for the internal `--help` flag (it can be invoked as `-h/--help` or as `-h/--help <taskname>`) and that still functions fine.

So this is likely a bug in the intersection of parser setup & task definition. I'll have to dig and see what's up (& why the test suite is missing this; probably because it tests at the parser-component level and may be lacking one at the task level.)

---

(N.B. The `kind` option mentioned refers to an argument's type, e.g. if you were explicitly specifying parser-level argument objects. That's not super well documented at the moment as it's currently used internally only.)

**Comment by bitprophet** [comment]
One big missing piece: the docs are lacking the part where *you must explicitly declare which arguments are 'optional'* because otherwise the parser can't tell whether a given arg should behave optionally or normally. (Having all arguments behave optionally would introduce too much ambiguity/confusion.)

What's missing from that conceptual parsing doc is a concrete example like so:

``` python
@task(optional=['new'])
def import_auth(ctx, new=False):
    pass
```

----

Naturally, of course, when I try to verify this...the behavior remains the same 😠 

Debugged a bit using `INVOKE_DEBUG=1 <command>`...

`inv --help foo`:

```
invoke.parser.parse_argv: Splitting x=y expr '-h=foo' into tokens '-h' and 'foo'
invoke.parser.handle: Handling token: '-h'
invoke.parser.handle: Saw flag '-h'
invoke.parser.switch_to_flag: Moving to flag <Argument: help (h) ?>
invoke.parser.handle: Handling token: 'foo'
invoke.parser.check_ambiguity: Testing flag value: None
invoke.parser.see_value: Setting flag <Argument: help (h) ?> to value 'foo'
invoke.parser.changing_state: ParseMachine: 'context' => 'end'
```

Notably, the correct/expected behavior of associating `foo` with its preceding `--help`. (Note the `?` in the `__str__` of `Argument`, which I just added to help doublecheck this feature.)

With `import_auth` defined as above and invoked as `inv import_auth --new=bluh`:

```
invoke.parser.parse_argv: Splitting x=y expr '--new=bluh' into tokens '--new' and 'bluh'
invoke.parser.handle: Handling token: '--new'
invoke.parser.handle: Saw flag '--new'
invoke.parser.switch_to_flag: Moving to flag <Argument: new (n) ?>
invoke.parser.switch_to_flag: Marking seen flag <Argument: new (n) ?> as True
invoke.parser.handle: Handling token: 'bluh'
invoke.parser.handle: Can't find context named 'bluh', erroring
```

So for some reason, even though both `Argument` objects have `optional=True` (as evidenced by the `?`), the help flag is working, while the `new` flag is behaving as a boolean-like flag instead of an optional, bool-or-str, flag.

----

Then I checked and, ok, *with* `@task(optional=['the-argument-in-question'])`, this behavior *is* because of the boolean default value.

If one does this:

``` python
@task(optional=['new'])
def import_auth(ctx, new='ugh'):
    pass
```

then it behaves as expected:

- `inv import_auth` shows `new=='ugh'`
- `inv import_auth --new` shows `new==True`
- `inv import_auth --new=whut` shows `new=='whut'`

----

So this is a dual issue:

- Missing/misleading docs, as stated
- Corner case of wanting to specify a non-string default value for an optional arg.
    - Don't know offhand how easy it will be to solve this...hopefully we can just add some explicitness to the logic so optionalness wins over booleanness.

**Comment by bitprophet** [comment]
Poked a little bit more while trying to update the docs w/ a realistic example...right, the reason this works well for `--help` is that it *does not set a default value at all* (which is possible because it's an explicit `Argument()` and not an implicitly-translated-from-func-signature one.)

Thankfully we can be explicit and say `def import_auth(ctx, new=None)`:

- Since `new=None` is the same as `Argument(name='new')` (i.e. the arg object's default-value attribute is `None` by default), the behavior is correct/identical to `--help`.
- Code testing the truthiness of `new` inside `import_auth()` will work the same as if it was `False`, as long as it is not explicitly saying e.g. `if new == True` or `if bool(new)` or etc.
    - Since those would be Python antipatterns, I'm not personally super bothered by this...
- As an alternative, you can also say `new=''`, which behaves identically, except of course that it is the empty string instead of `None` if the flag is not given at all. (And this, too, behaves 'falsey' in most situations, though `None` is generally considered to be a more Pythonic way to say "falsey and also indicates a value not given".)

**Comment by bitprophet** [comment]
So now the question is whether to make any non-doc changes...leaning 'yes' because even with clear docs showing a recommended default kwarg value of `None`, it's understandable why a user would try to slap `False` in there. Additionally, it's a code smell to have different types of values result in different behavior when you wouldn't naturally expect such a difference.

Depends on how easy it would be to change things w/o breaking other behavior...will see.

**Comment by bitprophet** [comment]
Poked more again, realized the truly salient bit is how `--help` has no explicit `kind` (and is thus default, `str`) but a from-task argument whose default value is `False` has a `kind` of `bool`.

And that's important because the logic we're tripping here is in `Parser.switch_to_flag` that asks `if not argument.takes_value`, which presently is the same as asking `if argument.kind is bool`.

**Comment by bitprophet** [comment]
All set, will be out in next bugfix release. Thanks again!
