### ISSUE TITLE
Custom exception to stop task cleanly

### ISSUE THREAD

**Issue by pekkaklarck** [pyinvoke/invoke#476]
It's pretty common that tasks fail due to invalid input or otherwise. If that happens on the top level of the task, you can simply do

```python
if something_went_wrong:
    print(message)
    return
```
but that's not too convenient if the problem occurs somewhere deeper in a utility function called by the main task. In these cases I tend to use

```python
if someting_went_wrong:
    raise ValueError(message)
```

but that results in annoying traceback on the command line. I could obviously catch the exception myself in the task, but adds extra boiler plate code to task definition files.

It would be great if Invoke provided a custom exception like `TaskFailed` that could he used in these cases. Invoke should then catch the exception and report it to the user without the traceback. Hiding tracebacks from all exceptions clearly wouldn't be a good idea as it makes debugging actual bugs harder.

If this kind of functionality already exists, just let me know where can I find it. I could find anything from docs and experiments with the existing `invoke.Failure` didn't go too well.

**Comment by chenull** [comment]
i usually do this:

```python
from invoke import task
from colorama import Fore, Style
from invoke.exceptions import ParseError

class Error(ParseError):
    def __init__(self, message):
        self.message = '{red}{cls}{r}: {message}'.format(
            red=Fore.RED + Style.BRIGHT,
            cls=self.__class__.__name__,
            r=Style.RESET_ALL,
            message=message
        )
        super().__init__(message)

    def __str__(self):
        return self.message

@task
def bw(ctx, node=None):
    try:
        5 / 0
    except ZeroDivisionError as e:
        raise Error(e)
```
Produces:

```
(liur)  $ liur bw
Error: division by zero
```

**Comment by bitprophet** [comment]
@pekkaklarck to clarify, what you want is still for overall execution to halt, and just for the final result to be a (Fabric 1-like, fwiw) error message without any messy traceback?

`Failure` used to allow that, but that behavior is now in a few subclasses _of_ `Failure`, including `UnexpectedExit`, which is what powers the behavior of `run` failures (they do exactly what you're describing, print a message and `sys.exit` w/o traceback.)

I think you may be able to use a related class, `Exit`, which is by-and-large the same as calling `sys.exit` (except of course it's a custom exception and can be treated differently when necessary.)

So try e.g. `raise Exit("oh noes what did you do")` - which will result in the CLI machinery calling `sys.exit("oh noes what did you do")`, which (due to how `sys.exit` is defined) will print that to stderr and exit 1.

I'm going to tentatively close this hoping that `Exit` is what you're looking for, but it's possible it doesn't quite fit (and we may need to make it more visible in the docs - it wasn't originally intended to be user-facing so it's only in the API docs) so let me know and I can reopen.

**Comment by bitprophet** [comment]
FWIW the exact code that powers this behavior is here: https://github.com/pyinvoke/invoke/blob/422de88afa5baa016721ab4852fa1a76ea528245/invoke/program.py#L294

The exception classes involved typically just add more dressing on top of having a `.code` which is what gets stuffed into `sys.exit`.

**Comment by bitprophet** [comment]
(ooh, snazzy inline snippets! nice, github!)

**Comment by pekkaklarck** [comment]
Thanks, `invoke.Exit` does exactly what I wanted. Got pretty close with my attempt to use `invoke.Failure`. =)

I would propose documenting in the user facing docs. Perhaps there could also be a separate exception exactly for this usage and with a name making the usage more explicit.

**Comment by bitprophet** [comment]
This got reported again barely a month later so I made that latest one a "update the docs" ticket.
