### ISSUE TITLE
My I know to to debug my task code in PyCharm?

### ISSUE THREAD

**Issue by namgivu** [pyinvoke/invoke#483]

**Comment by bitprophet** [comment]
Marking this closed since it's not really a code problem. I don't use PyCharm so can't help but if you're lucky another user will have an idea. For what it's worth, you should be able to use the Program or Executor classes to execute tasks from within Python, and we may add more API functionality for that once #170 is solved. Thanks!

**Comment by Aiky30** [comment]
@namgivu You can debug in PyCharm by creating a run task in the top right of the editor. This can be found next to the run and debug buttons under the option "Edit configurations". The "script" field would be the location of the invoke or fabric invoke.py file. The "script parameters" field would be the name of the task(s) which you want to run / debug.

Questions of this nature would be for Stack Overflow or a similar site for help as well as Pycharms documentation. 

https://stackoverflow.com/questions/10240018/how-to-use-pycharm-to-debug-python-script

**Comment by crbunney** [comment]
@Aiky30's suggestion didn't work for me on Windows using IntelliJ because the scripts install as `.exe`s not python files so weren't selectable in IntelliJ.

My slightly hacky solution was to temporarily add a `__main__` method to the `tasks.py` that called the task I wanted to debug and then debug `tasks.py` as normal. (I call it slightly hacky, because it involves adding something that I then have to remember to remove when I'm done which I'd rather not do)
