### ISSUE TITLE
feature request: inheritable tasks

### ISSUE THREAD

**Issue by plockaby** [pyinvoke/invoke#489]
Hello, feel free to close this if you're not taking feature requests.

In Fabric, you had "new-style Tasks" that were classes and I could build basic classes and have projects inherit those classes to do even more. I used it pretty extensively to create a build tool that I use at work: https://github.com/plockaby/clone-push

I am not seeing how to do that same capability to have inheritable tasks with invoke. I'd like to make a feature request for that capability.

I'm also not figuring out how to call tasks from other tasks outside of the dependencies syntax.

**Comment by bitprophet** [comment]
Apologies that this got past me when originally posted!

In Fab 2 / Invoke, [Task](http://docs.pyinvoke.org/en/1.0/api/tasks.html#invoke.tasks.Task) is publicly exposed/documented and is intended to be subclass-able. I'm afraid I don't have time to dive into your build tool's source right now, but if you can post specific issues you're having around juggling subclasses with Task and/or `@task`, please do!

I'll note that I ran across this because I was performing due diligence around a soon-to-be-merged minor new feature, adding a `klass` argument to `@task` (which IIRC Fab 1 also had) to allow for customized subclassing -- without this, using subclasses w/ decorator-driven task declaration is indeed kind of a pain. I'm _hoping_ this is what you ran into, in which case Invoke 1.1 should make it easier.

**Comment by plockaby** [comment]
Yes, I'm able to create inheritable tasks now. Have been since Fall 2018. Thanks for this great tool.
