### ISSUE TITLE
"." in task names

### ISSUE THREAD

**Issue by Ohjeah** [pyinvoke/invoke#499]
You cannot use `.` in your task name. This is neither documented [here](http://docs.pyinvoke.org/en/0.11.1/concepts/namespaces.html#naming-your-tasks) nor validated during task instantiation. 

Since the dot is used as a collection token invoke will eventually raise a `KeyError`.

Is there a way around this?

I was looking into Rake-like file tasks.

minimal example:

```python
from invoke import task

@task(name="a.name")
def f(ctx):
    pass
```

**Comment by bitprophet** [comment]
> Since the dot is used as a collection token

This is the core reason why (well, ok, the _real_ core reason is because tasks originate from `module.function` and/or `class.method`...). A dot signifies a subcollection boundary. I'm not sure it's technically feasible to change that at this time, but I haven't looked.

That said, I'm not sure I'd want to add it even if it's doable w/o breaking things, not least because there's a lot of ambiguity between `a.single.task.with.dots.in.it` and `outer_coll.inner_coll.taskname`.

Can you elaborate on your use case some more? What's the real set of tasks you want to define here, and why do you want a single task named `a.name` and don't want to get there via an `a` collection containing a `name` task (resulting in an invocable `a.name`)?

**Comment by Ohjeah** [comment]
I was looking into Rake-like file tasks and rules.

Often I do

```ruby
Files = FileList[...]
task "main.pdf" => Files
# or
rule ".pdf" => ".tex"
```

So I would need the dot to `invoke main.pdf`.  Filetasks don't get executed if the file exists and its modification timestamp is younger than all its depend ones. Rules are fallbacks for Filetasks.

**Comment by SwampFalc** [comment]
Well... Invoke has the option to declare one task to be default.

So you could create a handle_file task, which takes one filename argument, and label it as default. Since dots are permitted in task arguments, that should give you the same user interface.

**Comment by Ohjeah** [comment]
Sure you can do it manually, but for me this boilerplate stuff should go into the library.

**Comment by bitprophet** [comment]
We're getting closer now...I haven't used Rake in years and certainly haven't used that particular feature. From context I'm assuming the deal is that there's one "task" named `main` and it has multiple "flavors" generating different file types, thus the dots? (Since they seem to just map to file extensions?)

It's a new concept to me for sure and isn't something others have brought up. I'm still leaning towards "doesn't seem to add enough or be widely applicable enough to merit being confusing or breaking other behavior" unfortunately.

For example, unless I'm still missing an aspect of the 'File' behavior (seems plausible...), you could largely replicate it with a simple flag, eg:

``` python
@task
def main(c, ext):
  content = load_source()
  if ext == 'pdf':
    write_pdf(content)
  elif ext == 'tex':
    write_tex(content)
```

Invoked as:

```
$ inv main -e pdf
```

or etc. Yes, it's a few more characters on the invocation vs `inv main.pdf`, but it's still very clear and straightforward, and isn't conflated with the existing meaning of the dot. (Granted, each 'version' of the task does not appear as distinct tasks in `--list`, which is a downside.)

There's also the option to leverage actual collections (or, probably a closer match, the not yet implemented #347 - tl;dr s/module-and-functions/class-and-methods) which even fixes that angle:

``` python
def main_(c, ext):
  # same as above, probably

@task
def pdf(c):
  main_(c, 'pdf')

@task
def tex(c):
  main_(c, 'tex')

ns = Collection('main', pdf, tex)
```

Result:

```
$ inv -l
main.pdf
main.tex
$ inv main.pdf
<PDF written>
```

**Comment by Ohjeah** [comment]
From the [apidocs](https://ruby-doc.org/stdlib-1.9.3/libdoc/rake/rdoc/Rake/FileTask.html)

> A FileTask is a task that includes time based dependencies. If any of a FileTask’s prerequisites have a timestamp that is later than the file represented by this task, then the file must be rebuilt (using the supplied actions).

Let's stick with the main.pdf example.
The task is main.pdf. I indicate that it is a FileTask making it depend on "main.tex"

```
task "main.pdf" => "main.tex" do |t|
    sh "pdflatex #{t.source}"
end
```
With "rake main.pdf". I can invoke the task. I also have symbolic access to the source files.

This indicates that my FileTask depends on main.tex file. Hence it is only executed if the main.pdf file does not exist or if it is outdated.

You extend this idea of dependencies to multiple sources.

In invoke you would define the task list this:

```python
@task
def main(ctx):
    sources = ["main.tex"]
    mod_time = os.path.getmtime("main.pdf")
    if not os.path.exits("main.pdf") or any(os.path.getmtime(s) < mod_time for s in sources):
        ctx.run("pdflatex main.tex")
```
Notice the three lines of boilerplate which should belong to the library.


It get's even more compact. In Rake (and Make) I can use rules:

```ruby
rule ".pdf" => ".tex" do |t|
    sh "pdflatex #{t.source}"
end
```

This still let's me invoke `rake main.pdf` but also `rake main2.pdf` if there is a `main2.tex`.

**Comment by bitprophet** [comment]
Sounds like much of that belongs in #461 :)

**Comment by Ohjeah** [comment]
I have to read through that issue. It's pretty lengthy :-)

Another point of though:

Currently, the task object needs to exist to make a task depend on it. If you have rule based task discovery, that task object would be created after parsing the task.py file.

**Comment by Ohjeah** [comment]
You can also chain rules likes this:

```ruby
rule ".md" do |t|
    sh "echo #{t.name} > #{t.name}"
end

rule ".pdf" => ".md" do |t|
    sh "pandoc #{t.source} -o #{t.name}"
end
```

and `rake 3.pdf`.

Maybe you can put this in #461 as well, but you would still need the dot in file names. You basically use `".".join` and `.split(".")` why not replace "." by any other token?
