### ISSUE TITLE
default value for positional argument

### ISSUE THREAD

**Issue by antoine-gallix** [pyinvoke/invoke#554]
I've been playing with `optional` and `positional` arguments of the `task` decorator, but I cannot find a way to achieve to following. I have a function that run scripts that are placed in a folder. I want to be able to run scripts by name, and list the available scripts. I'd like to achieve the following:

```
inv run_script script_name
> run the given script
inv run_script --list
> print list of available scripts
```

Up to now, I could only manage this with an optional argument:

```
inv run_script --name script_name
> run the given script
inv run_script --list
> print list of available scripts
```

My question is : How can I make an argument be both positional, and have a default value?

**Comment by plockc** [comment]
from the docs (http://www.pyinvoke.org/), you can run multiple tasks with one `invoke` command, which I think means no positional arguments:
"From GNU Make, it inherits an emphasis on minimal boilerplate for common patterns and the ability to run multiple tasks in a single invocation:"
`$ invoke clean build`

**Comment by bitprophet** [comment]
@plockc Not quite, there is both implicit and explicit support for positional arguments - but the multi-task nature of the parser is why it has to be handled carefully so it knows when a token is a positional argument value, and when it should signal looking for the next task 'context'.

@antoine-gallix I _think_ what you're describing -- a positional but also optional (because it has a default value) argument -- falls under an outstanding issue, #159, which is somewhere in the middle of my "top issues" priority list. Going to close this as a duplicate on those grounds but feel free to correct me if I'm not looking closely enough. Thanks!

**Comment by plockc** [comment]
I hadn't played with the positional arguments to Task yet and didn't read clearly enough, my bad @antoine-gallix

**Comment by antoine-gallix** [comment]
Just for info, the collection default task option finally also fits my requirements:

```
inv run.script script_name
> run the given script. default task for "script" collection
inv run.script.list
> print list of available scripts
```

**Comment by jlugao** [comment]
hey @antoine-gallix I am looking for exactly this, could you share a gist of how you've set up the project? I am new to invoke and couldn't figure out for myself
I was using a makefile to manage my projects shortcuts, but the argument passing was not smooth so I am migrating to Invoke

**Comment by antoine-gallix** [comment]
@jlugao 
```python
namespace = Collection()

script = Collection('script')


@task
def list_scripts(ctx):
	....

script.add_task(list_db_scripts, 'list')

@task
def run_script(ctx, name):
	....

script.add_task(run_script, 'run', default=True)

namespace.add_collection(script)
```

```shell
invoke script.run <script_name>
invoke script <script_name>
# both run the run_script command
invoke script.list
# run a list_script command
```

**Comment by olance** [comment]
@jlugao @antoine-gallix I have just pushed a PR #635 that adds support for this :)
