### ISSUE TITLE
Allow arbitrary shells

### ISSUE THREAD

**Issue by brejoc** [pyinvoke/invoke#67]
Make sure users can determine which local shell is used when executing commands.

----

Was: *Only Bash as shell?*

> I've only had a quick peek at the code, but I think the bash shell is hardcoded in the runner. Would be nice to let the user define the the shell in tasks.py, since some shells don't share the same syntax.

**Comment by bitprophet** [comment]
Ran into an internal need for this in #152 (see final comment), so, poking now.

The tl;dr of current state of this issue:

* Configuration has been in for a long time now (this ticket is old) so not a problem
* PTY-driven `run` sets its own shell, which is `/bin/bash`, so that's easily updated
* non-PTY-driven `run` uses `subprocess`' own hardcoded default, `/bin/sh`, but that should be overrideable via the `executable` kwarg

**Comment by bitprophet** [comment]
All done. Simply configure `run.shell` via any config method, or say `run('command', shell='/bin/fish')` or whatnot at runtime.

**Comment by presidento** [comment]
Great, thank you @bitprophet!
(Didn't you want to add it to the 0.12.3 milestone?)

**Comment by frol** [comment]
Just for your info, the implementation of this feature breaks Invoke on Windows: #345.
