### ISSUE TITLE
sdist 1.7.0 is missing vendor/yaml2

### ISSUE THREAD

**Issue by ndparker** [pyinvoke/invoke#850]
Hi,

for some reason the yaml2 path is missing (making it impossible to use this version with python 2). I'm wondering how the source dist was created, because setup.py sdist from the github checkout apparently includes it in the tarball.

Cheers,

**Comment by neozenith** [comment]
Thanks for reporting this. To be clear, what are the exact steps to replicate this?

**Comment by neozenith** [comment]
Ok rather than being lazy I quickly checked:

The file located at:
https://pypi.org/project/invoke/1.7.0/#files
In particular this file:
https://files.pythonhosted.org/packages/55/a2/763dc56e746ca013061b26c95868cb7f832c2a87dc27ed749641a734957f/invoke-1.7.0.tar.gz

Does only contain `vendor/yaml3` and not `vendor/yaml2`.

There was this note in the changelog though:
https://github.com/pyinvoke/invoke/tree/1.7.0
> Warning
> Due to various factors, this release will not include a Python 2-compatible wheel archive. Users of Python 2 can still install from the sdist, and are strongly encouraged to check [the roadmap](https://bitprophet.org/projects/#roadmap) as the next release will likely be the one that removes Python 2 entirely!

Which would lead me to believe the above file from PyPI should work for Python2 as expected.

I believe it is this line in `setup.py` that has dropped the `yaml2` path in the `.tar.gz`
https://github.com/pyinvoke/invoke/blob/main/setup.py#L17

I can confirm that in the interim the following works:

```
python -m pip install https://github.com/pyinvoke/invoke/archive/1.7.zip
```

**Comment by bitprophet** [comment]
That's unfortunate that the tarball still ended up with the wrong yaml version 🤦🏻   unfortunately all of the environments I build with have left Python 2 behind and as the changelog notes, the next release will drop Python 2 support entirely - so I can't really spend time on fixing this. Apologies!
