### ISSUE TITLE
Windows 

### ISSUE THREAD

**Issue by VVE** [pyinvoke/invoke#858]
can Fabric be used for windows hosts?

**Comment by neozenith** [comment]
Hi,

This question is possibly best answered under the Fabric project pages instead of the Invoke pages:
 - https://www.fabfile.org/index.html
 - https://github.com/fabric/fabric

But a quick search of stackoverflow lead to this:
https://stackoverflow.com/questions/9000380/install-python-fabric-on-windows

The related questions might be helpful.
